### PR TITLE
feat: add support for index jsx/tsx files in modules

### PR DESCRIPTION
**Pull request by robertoyoc**
Solves https://github.com/antoine-coulon/skott/issues/120

### CODE REVIEW

**Review by antoine-coulon — COMMENTED** [review]
Thanks for contributing! Implementation looks good to me. Could you just please add some unit tests covering the behavior? This is a pretty critical part of the resolution algorithm and all cases should be covered and ES spec compliant (the order in which modules are resolved). This part is meant to be improved in the near future and having tests for all cases expected would be clutch.

I think we need to have unit tests covering at minimum these cases:

For TypeScript:
- Given a import to `./`, if there is **only** an existing module `index.tsx` in the directory then it should resolve to that module
- **index.ts** should always be resolved in priority over **index.tsx** that is given **index.tsx** and **index.ts** existing in a directory, any module import such as `./` or  `.` should resolve to **index.ts**

For JavaScript:
- Given a import to `./`, if there is **only** an existing module `index.jsx` in the directory then it should resolve to that module
- **index.js** should always be resolved in priority over **index.jsx** that is given **index.jsx** and **index.js** in a directory, any module import such as `./` or  `.` should resolve to **index.js**.

There is a test suite in `packages/skott/test/unit/ecmascript/jsx-and-tsx.ts` that already covers cases mixing JS/JSX and TS/TSX so you might just need to add test cases there.

**Comment by antoine-coulon** [comment]
Once the tests are added, could you also please add a changeset to this PR, I think this should be annotated as a patch version.

For that at the root of the workspace you can run:

```
pnpm changeset
```

Select "skott" for a patch version update and describe what was added there. 
Thanks!

**Comment by robertoyoc** [comment]
I'll follow your instructions and push later @antoine-coulon 👍

**Comment by robertoyoc** [comment]
@antoine-coulon let me know if anything else needed

**Review by antoine-coulon — APPROVED** [review]
Awesome LGTM, thanks for contributing!

**Pull request merged**
